### ISSUE TITLE
Every command results in "no current authenticated user"

### ISSUE THREAD

**Issue by weskerfoot** [blue-yonder/devpi-cleaner#118]
I try running, e.g. 

```
devpi-cleaner --password foobar --login ci myserver.local 'package'
```

and I get a traceback

```
Traceback (most recent call last):
  File "/home/wes/.local/bin/devpi-cleaner", line 8, in <module>
    sys.exit(main())
  File "/home/wes/.local/lib/python3.9/site-packages/devpi_cleaner/cli.py", line 37, in main
    with DevpiClient(args.server, login_user, password) as client:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi_plumber/client.py", line 31, in DevpiClient
    wrapper = DevpiCommandWrapper(url, client_dir, client_cert=client_cert)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi_plumber/client.py", line 47, in __init__
    self.use(urlsplit(url)[2])
  File "/home/wes/.local/lib/python3.9/site-packages/devpi_plumber/client.py", line 78, in use
    result = self._execute('use', url, **kwargs)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi_plumber/client.py", line 67, in _execute
    devpi(args)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi/use.py", line 390, in main
    current.configure_fromurl(hub, url, client_cert=args.client_cert)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi/use.py", line 190, in configure_fromurl
    url = self.get_index_url(url)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi/use.py", line 309, in get_index_url
    return self.get_user_url().addpath(indexname)
  File "/home/wes/.local/lib/python3.9/site-packages/devpi/use.py", line 300, in get_user_url
    raise ValueError("no current authenticated user")
ValueError: no current authenticated user
```

I can log in just fine using the regular `devpi` commands.

Could be because of API changes?

**Comment by matthias-bach-by** [comment]
We utilise the upstream Devpi Client under the hood. Thus, if it works with the Devpi Client installed in the same Python environment, it should not be due to an API mismatch.

**Comment by matthias-bach-by** [comment]
I just happened to run into exactly the same issue. Does your server operate on HTTPS? By default the client assumes HTTP, and following redirects it seems to get into a weird state where it assumes it should be logged in (it send the credentials), but doesn't actually get back a valid session. Explicitly specifying the protocol for the server solves that. 
```
devpi-cleaner --password foobar --login ci https://myserver.local 'package'
```

**Comment by weskerfoot** [comment]
> I just happened to run into exactly the same issue. Does your server operate on HTTPS? By default the client assumes HTTP, and following redirects it seems to get into a weird state where it assumes it should be logged in (it send the credentials), but doesn't actually get back a valid session. Explicitly specifying the protocol for the server solves that.
> 
> ```
> devpi-cleaner --password foobar --login ci https://myserver.local 'package'
> ```

at the time I don't think it was using https, it is now and works fine as far as I know, so I think you're correct

**Comment by matthias-bach-by** [comment]
In this case I am closing this as, while I admit that UX is suboptimal in this case, I currently neither have the capacity nor a good idea on how to improve UX here. We can re-open this in case anybody else get's stuck here.
